Migrated pipelines from Jenkins to Github Actions     - There are 2 main jobs now:         - full-build-with-disabled-tests         - run-tests     - The first job builds all the services without     running any tests and uploads the packages in     Github Packages     - The second job runs Janssen Monolith and     executes all the needed preparations and tests     for the services inside of a docker container.     After this the results from the tests are being     copied to the Github Runner machine and uploaded     in the repo.

diff --git a/.github/workflows/full-rebuild.yml b/.github/workflows/full-rebuild.yml
--- a/.github/workflows/full-rebuild.yml
+++ b/.github/workflows/full-rebuild.yml
@@ -1,144 +1,183 @@
-name: Full Rebuild with Disabled Tests
+name: Jans Full Build 
 
 on:
+  push:
+    branches:
+      - main
+  schedule:
+    - cron: '0 8 * * *'
+  pull_request:
+    branches:
+      - main
   workflow_dispatch:
-    inputs:
-      VERSION_NAME:
-        description: 'Which version should be used'
-        required: true
-        type: string
-      MAVEN_SKIP_TESTS:
-        description: 'Set to true if need to trigger build without tests execution'
-        required: true
-        type: boolean
-      PROFILE_NAME:
-        description: 'Profile name which build should use'
-        required: false
-        type: string
-      CONTAINER_NAME:
-        description: 'LXC container name. Examples: ubuntu20-ldap, ubuntu20-couchbase, ubuntu20-mysql, ubuntu20-spanner'
-        required: false
-        type: string
-      DEVELOPMENT_BUILD:
-        description: 'Enabled or disable TRACE log level'
-        required: false
-        type: boolean
-      DEPLOY_BUILD:
-        description: 'Enabled or disable war file deployment'
-        required: false
-        type: boolean
-      SKIP_FINDBUGS:
-        description: 'Skip findbug check'
-        required: false
-        type: boolean
-      CVSS_SCORE:
-        description: 'Common Vulnerability Scoring System SIG'
-        required: false
-        type: boolean
-      DEPENDENCY_CHECK:
-        description: 'Enable OWASP check'
-        required: false
-        type: boolean
-      TEST_CONF_IN_HOST:
-        description: 'Is test profile location in host or in lxc'
-        required: false
-        type: boolean
+
 
 jobs:
-  trigger-workflows:
+  # full-build-with-disabled-tests:
+  #   runs-on: ubuntu-20.04
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   env:
+  #     VERSION_NAME: main
+  #     MAVEN_SKIP_TESTS: true
+  #     PROFILE_NAME: "default"
+
+  #   strategy:
+  #     max-parallel: 1
+  #     matrix:
+  #       service:
+  #         - "jans-bom"
+  #         - "jans-orm"
+  #         - "jans-core"
+  #         - "jans-lock/lock-master"
+  #         - "agama"
+  #         - "jans-auth-server"
+  #         - "jans-link"
+  #         - "jans-fido2"
+  #         - "jans-scim"
+  #         - "jans-keycloak-link"
+  #         - "jans-config-api"
+  #         - "jans-keycloak-integration"
+  #         - "jans-casa"
+
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v4
+  #     with:
+  #       ref: ${{ github.event.inputs.branch }}
+
+  #   - name: Set up Java 17
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: '17'
+  #       distribution: 'adopt'
+
+  #   - name: Set up Maven
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: '17'
+  #       distribution: 'adopt'
+  #       cache: 'maven'
+
+  #   - name: Build ${{ matrix.service }}
+  #     run: |
+  #       if [ "${{ github.event_name }}" == "pull_request" ]; then
+  #         mvn -f ${{ matrix.service }}/pom.xml -Dcfg=${{ env.PROFILE_NAME }} -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} clean install -Drevision=${{ github.head_ref }}-SNAPSHOT
+  #       else
+  #         mvn -f ${{ matrix.service }}/pom.xml -Dcfg=${{ env.PROFILE_NAME }} -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} clean install
+  #       fi
+
+  #   - name: Publish to GitHub Packages
+  #     run: mvn -B deploy -Dmaven.test.skip=${{ env.MAVEN_SKIP_TESTS }} -Dcfg=${{ env.PROFILE_NAME }}
+  #     working-directory: ${{ matrix.service }}
+  #     env:
+  #       GITHUB_TOKEN: ${{ secrets.JANS_TOKEN }}
+
+  #   - name: Archive results
+  #     if: always()
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: build-results
+  #       path: ${{ matrix.service }}/target
+
+  #   - name: Send notification on failure
+  #     if: failure()
+  #     run: echo "Build failed"
+
+  # cleanup:
+  #   if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
+  #   runs-on: ubuntu-20.04
+  #   steps:
+
+  #   - name: Clean up PR assets
+  #     run: |
+  #       # List all SNAPSHOT versions
+  #       versions=$(curl -s -H "Authorization: token ${{ secrets.JANS_TOKEN }}" "https://maven.pkg.github.com/DanielKoklev/jans/maven-metadata.xml" | grep -oP '(?<=<version>)[^<]+')
+        
+  #       for version in $versions; do
+  #         if [[ $version == *-SNAPSHOT ]]; then
+  #           # Delete the version from GitHub Packages
+  #           curl -X DELETE -H "Authorization: token ${{ secrets.JANS_TOKEN }}" "https://maven.pkg.github.com/DanielKoklev/jans/io/jans/${{ matrix.service }}/$version"
+  #         fi
+  #       done
+
+  run-tests:
+    permissions: write-all
     runs-on: ubuntu-20.04
-
+    env:
+      MAVEN_SKIP_TESTS: false
+      CONTAINER_NAME_SPANNER: ubuntu20-spanner
+      CONTAINER_NAME_CB: ubuntu20-couchbase
+      CONTAINER_NAME_LDAP: ubuntu20-ldap
+      CONTAINER_NAME_MYSQL: ubuntu20-mysql
+      CONTAINER_NAME_POSTGRESQL: ubuntu20-postgresql
+      DEVELOPMENT_BUILD: true
+      SKIP_FINDBUGS: true
+      DEPENDENCY_CHECK: true
+      VERSION_NAME: main
+      PROFILE_NAME: default
+    strategy:
+      max-parallel: 5
+      matrix:
+        persistence:
+          # - "LDAP"
+          # - "MYSQL"
+          - "PGSQL"
+          # - "COUCHBASE"
+          # - "SPANNER"
+      fail-fast: false
     steps:
+
     - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Trigger jans-bom workflow
-      uses: benc-uk/workflow-dispatch@v1
+      uses: actions/checkout@v4
       with:
-        workflow: 'jans-bom.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}'
+        ref: ${{ github.event.inputs.branch }}
+
+    - name: Set up Java 17
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'adopt'
+
+    - name: Set up Maven
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'adopt'
+        cache: 'maven'
+
+    - name: Run Jans Monolith
+      env:
+        JANS_FQDN: demoexample.jans.io
+        EXT_IP: $(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
+        JANS_BUILD_COMMIT: main
+      run: |
+        export ip=$(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
+        sudo chmod a+x automation/startjanssenmonolithdemo.sh
+        sudo RUN_TESTS=true bash ./automation/startjanssenmonolithdemo.sh "demoexample.jans.io" "${{ matrix.persistence }}" "$ip" "${{ github.sha }}"
+
+    - name: List Reports
+      run: |
+        ls /tmp/reports/
+
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ matrix.persistence }}-test-results
+        path: /tmp/reports
     
-    - name: Trigger jans-orm workflow
-      uses: benc-uk/workflow-dispatch@v1
+    - name: Publish Test Report ${{ matrix.persistence }}
+      uses: starburstdata/action-testng-report@v1
       with:
-        workflow: 'jans-orm.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
+          report_paths: /tmp/reports/${{ matrix.persistence }}*.xml
+          github_token: ${{ github.token }}
+          fail_if_empty: false
 
-    - name: Trigger jans-core workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-core.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
+    # - name: Publish Test Report Surefire
+    #   uses: scacap/action-surefire-report@v1
+    #   if: success() || failure()
+    #   with:
+    #     github_token: ${{ github.token }}
+    #     report_paths: /tmp/reports/**.xml
 
-    - name: Trigger jans-lock workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-lock.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"PROFILE_NAME": "${{ github.event.inputs.PROFILE_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-agama workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-agama.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"PROFILE_NAME": "${{ github.event.inputs.PROFILE_NAME }}"}, {"CONTAINER_NAME": "${{ github.event.inputs.CONTAINER_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-auth-server workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-auth-server.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"PROFILE_NAME": "${{ github.event.inputs.PROFILE_NAME }}"}, {"CONTAINER_NAME": "${{ github.event.inputs.CONTAINER_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-link workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-link.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-fido2 workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-fido2.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"PROFILE_NAME": "${{ github.event.inputs.PROFILE_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-scim workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-scim.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"PROFILE_NAME": "${{ github.event.inputs.PROFILE_NAME }}"}, {"CONTAINER_NAME": "${{ github.event.inputs.CONTAINER_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-keycloak-link workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-keycloak-link.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-config-api workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-config-api.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"PROFILE_NAME": "${{ github.event.inputs.PROFILE_NAME }}"}, {"CONTAINER_NAME": "${{ github.event.inputs.CONTAINER_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-keycloak workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-keycloak.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
-
-    - name: Trigger jans-casa workflow
-      uses: benc-uk/workflow-dispatch@v1
-      with:
-        workflow: 'jans-casa.yml'
-        token: ${{ secrets.GITHUB_TOKEN }}
-        inputs: '{"VERSION_NAME": "${{ github.event.inputs.VERSION_NAME }}"}, {"MAVEN_SKIP_TESTS": "${{ github.event.inputs.MAVEN_SKIP_TESTS }}"}'
